services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: circle-intersection:local
    stdin_open: true
    tty: true

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: circle-intersection-test:local
